site_name: Tôi luyện Tiếng Anh - Khu học mở. 
site_description: Tự học Tiếng Anh thông qua tiêu thụ nội dung (media) như Phim, Sách, Báo, Game, Youtube
site_author: duykhanh471  
site_url: https://daihocmo.github.io/tieng-anh/

nav:
  - 'Lộ trình':
    - 'Các giai đoạn chính': 'guide.md'
  - 'Hướng dẫn':
    - 'Comprehensible Input': 'input.md'
    - 'Immersion': 'immersion.md'
  - 'Cài đặt':  
    - 'Cài đặt': 'setup.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
  - 'Cộng đồng':
    - 'Cộng đồng': 'cong-dong.md'
  - 'Nội dung Tiếng Anh':
    - 'Youtube': 'youtube.md'
    - 'Sách': 'sach.md'
    - 'Podcasts & Sách nói': 'podcasts.md'
      
theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.suggest
  name: material

plugins:
  - open-in-new-tab
  
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fbHbQSwzpD
  homepage: https://daihocmo.github.io/
  generator: false