site_name: Tự luyện Tiếng Anh - Khu học mở. 
site_description: Tự học Tiếng Anh các kiểu, chắc vậy.
site_author: duykhanh471  
site_url: https://daihocmo.github.io/tieng-anh/
repo_url: https://github.com/daihocmo/tieng-anh
repo_name: Đóng góp và chỉnh sửa trang

nav:
  - 'Trang chủ': 
    - 'Trang chủ': 'index.md'
    - 'Trước khi bắt đầu': 'truoc-khi-bat-dau.md'
    - 'Tham gia cộng đồng': 'join.md'
  - 'Hướng dẫn':
    - 'Tự học Tiếng Anh': 'guide.md'
    - '30 Ngày Tiếng Anh': '30ngay.md'
    - 'Nói Tiếng Anh': 'speaking.md'
    - 'Đọc Tiếng Anh': 'reading.md'
    - 'Hướng dẫn đơn ngữ': 'monolingual.md'
  - 'FAQ': 
    - 'FAQ về Tiếng Anh': 'faq.md'
  - 'Setup':  
    - 'Mining': 'setup.md'
    - 'Goldendict': 'goldendict.md'
    - 'Yomitan': 'yomitan.md'
  - 'Novel':
    - 'Web Novel': 'webnovel.md'
    - 'Visual Novel': 'vn.md'
  - 'Media': 'media-tieng-anh.md' 
  - 'Tài nguyên học':
    - 'Tài nguyên': 'resources.md'
    - 'Đầu vào dễ hiểu': 'input.md'
  - 'Những thứ khác':
    - 'Về Input': 'input.md'
    - 'Các nội dung khác': 'misc.md'


      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/english.svg
  favicon: assets/favicon.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  # - open-in-new-tab

extra:
  generator: false