site_name: Tôi luyện Tiếng Anh - Khu học mở. 
site_description: Tự học Tiếng Anh thông qua tiêu thụ nội dung (media) như Phim, Sách, Báo, Game, Youtube
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - 'Lộ trình':
    - 'Các giai đoạn chính': 'guide.md'
  - 'Hướng dẫn':
    - 'Comprehensible Input': 'input.md'
    - 'Immersion': 'immersion.md'
  - 'Cài đặt'  
    - 'Cài đặt': 'setup.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
  - 'Gợi ý':
    - 'Cộng đồng học': 'cong-dong.md'
    - 'IELTS': 'ielts.md'
  - 'Nội dung tiêu thụ':
    - 'Youtube': 'youtube.md'
    - 'Sách': 'sach.md'
    - 'Podcasts & Sách nói': 'podcasts.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false